vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    student_image:
      uri_prefix: /images/students
      upload_destination: "%kernel.project_dir%/public/images/students"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
