vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    student_image:
      uri_prefix: /images/students
      upload_destination: "%kernel.project_dir%/public/images/students"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    student_cv:
      uri_prefix: /uploads/cvs
      upload_destination: "%kernel.project_dir%/public/uploads/cvs"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    entreprise_image:
      uri_prefix: /uploads/entreprises
      upload_destination: "%kernel.project_dir%/public/uploads/entreprises"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
