# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
  db_driver: orm

  mappings:
    products:
      uri_prefix: /images/students
      upload_destination: "%kernel.project_dir%/public/images/students"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
